# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  # reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset

  # nice view
  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter_rgb nice_epaper
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: central_left_nice_view

  - board: nice_nano_v2
    shield: sofle_left nice_view_adapter_rgb nice_epaper
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: peripheral_left_nice_view

  - board: nice_nano_v2
    shield: sofle_right nice_view_adapter_rgb nice_epaper
    artifact-name: peripheral_right_nice_view

  # oled
  - board: nice_nano_v2
    shield: sofle_dongle dongle_display_091_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: central_dongle_oled_091

  - board: nice_nano_v2
    shield: sofle_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: central_dongle_oled

  - board: nice_nano_v2
    shield: sofle_left nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: central_left_oled

  - board: nice_nano_v2
    shield: sofle_left nice_oled
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: peripheral_left_oled 

  - board: nice_nano_v2
    shield: sofle_right nice_oled
    artifact-name: peripheral_right_oled
